### ISSUE TITLE
Invalid difference object

### ISSUE THREAD

**Issue by phildionne** [n9s/nucleotides#8]
When a model changes, the difference object being passed appears to be invalid.

Here's a naive way to reproduce:

```javascript
model = {
  permissions: [
    {
      id: 1,
      types: ['a', 'b']
    }
  ]
}

model.permissions[0].types.push('c')

// Difference object being passed on
{
  permissions: {
    types: {
      added: ['c']
    }
  }
}
```

As a suggestion, the difference logic could take inspiration from immutability-helper's API: https://github.com/kolodny/immutability-helper#update

**Comment by matehat** [comment]
Differences are now tracked properly in https://github.com/n9s/nucleotides/blob/master/src/difference.js, and changesets are formalized as https://github.com/n9s/nucleotides/blob/3f3fd962e0bb9ae2de4c3e845933062e2dfc4322/src/difference.js#L6, which can be inspected and applied to other objects
